// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddIndividualCreatedCode is the HTTP code returned for type AddIndividualCreated
const AddIndividualCreatedCode int = 201

/*AddIndividualCreated item created

swagger:response addIndividualCreated
*/
type AddIndividualCreated struct {
}

// NewAddIndividualCreated creates AddIndividualCreated with default headers values
func NewAddIndividualCreated() *AddIndividualCreated {
	return &AddIndividualCreated{}
}

// WriteResponse to the client
func (o *AddIndividualCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddIndividualBadRequestCode is the HTTP code returned for type AddIndividualBadRequest
const AddIndividualBadRequestCode int = 400

/*AddIndividualBadRequest invalid input, object invalid

swagger:response addIndividualBadRequest
*/
type AddIndividualBadRequest struct {
}

// NewAddIndividualBadRequest creates AddIndividualBadRequest with default headers values
func NewAddIndividualBadRequest() *AddIndividualBadRequest {
	return &AddIndividualBadRequest{}
}

// WriteResponse to the client
func (o *AddIndividualBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddIndividualConflictCode is the HTTP code returned for type AddIndividualConflict
const AddIndividualConflictCode int = 409

/*AddIndividualConflict an existing item already exists

swagger:response addIndividualConflict
*/
type AddIndividualConflict struct {
}

// NewAddIndividualConflict creates AddIndividualConflict with default headers values
func NewAddIndividualConflict() *AddIndividualConflict {
	return &AddIndividualConflict{}
}

// WriteResponse to the client
func (o *AddIndividualConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
