// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddBiosampleHandlerFunc turns a function with the right signature into a add biosample handler
type AddBiosampleHandlerFunc func(AddBiosampleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddBiosampleHandlerFunc) Handle(params AddBiosampleParams) middleware.Responder {
	return fn(params)
}

// AddBiosampleHandler interface for that can handle valid add biosample params
type AddBiosampleHandler interface {
	Handle(AddBiosampleParams) middleware.Responder
}

// NewAddBiosample creates a new http.Handler for the add biosample operation
func NewAddBiosample(ctx *middleware.Context, handler AddBiosampleHandler) *AddBiosample {
	return &AddBiosample{Context: ctx, Handler: handler}
}

/*AddBiosample swagger:route POST /biosample/{biosampleId} addBiosample

adds a biosample

Adds a biosample to the system

*/
type AddBiosample struct {
	Context *middleware.Context
	Handler AddBiosampleHandler
}

func (o *AddBiosample) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddBiosampleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
