// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddIndividualHandlerFunc turns a function with the right signature into a add individual handler
type AddIndividualHandlerFunc func(AddIndividualParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddIndividualHandlerFunc) Handle(params AddIndividualParams) middleware.Responder {
	return fn(params)
}

// AddIndividualHandler interface for that can handle valid add individual params
type AddIndividualHandler interface {
	Handle(AddIndividualParams) middleware.Responder
}

// NewAddIndividual creates a new http.Handler for the add individual operation
func NewAddIndividual(ctx *middleware.Context, handler AddIndividualHandler) *AddIndividual {
	return &AddIndividual{Context: ctx, Handler: handler}
}

/*AddIndividual swagger:route POST /individuals/{individualId} addIndividual

adds an individual item

Adds an individual to the system

*/
type AddIndividual struct {
	Context *middleware.Context
	Handler AddIndividualHandler
}

func (o *AddIndividual) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddIndividualParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
