// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddResultdetailsCreatedCode is the HTTP code returned for type AddResultdetailsCreated
const AddResultdetailsCreatedCode int = 201

/*AddResultdetailsCreated item created

swagger:response addResultdetailsCreated
*/
type AddResultdetailsCreated struct {
}

// NewAddResultdetailsCreated creates AddResultdetailsCreated with default headers values
func NewAddResultdetailsCreated() *AddResultdetailsCreated {
	return &AddResultdetailsCreated{}
}

// WriteResponse to the client
func (o *AddResultdetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddResultdetailsBadRequestCode is the HTTP code returned for type AddResultdetailsBadRequest
const AddResultdetailsBadRequestCode int = 400

/*AddResultdetailsBadRequest invalid input, object invalid

swagger:response addResultdetailsBadRequest
*/
type AddResultdetailsBadRequest struct {
}

// NewAddResultdetailsBadRequest creates AddResultdetailsBadRequest with default headers values
func NewAddResultdetailsBadRequest() *AddResultdetailsBadRequest {
	return &AddResultdetailsBadRequest{}
}

// WriteResponse to the client
func (o *AddResultdetailsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddResultdetailsConflictCode is the HTTP code returned for type AddResultdetailsConflict
const AddResultdetailsConflictCode int = 409

/*AddResultdetailsConflict an existing item already exists

swagger:response addResultdetailsConflict
*/
type AddResultdetailsConflict struct {
}

// NewAddResultdetailsConflict creates AddResultdetailsConflict with default headers values
func NewAddResultdetailsConflict() *AddResultdetailsConflict {
	return &AddResultdetailsConflict{}
}

// WriteResponse to the client
func (o *AddResultdetailsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
