// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePatientOKCode is the HTTP code returned for type DeletePatientOK
const DeletePatientOKCode int = 200

/*DeletePatientOK Deleted item

swagger:response deletePatientOK
*/
type DeletePatientOK struct {
}

// NewDeletePatientOK creates DeletePatientOK with default headers values
func NewDeletePatientOK() *DeletePatientOK {

	return &DeletePatientOK{}
}

// WriteResponse to the client
func (o *DeletePatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletePatientMethodNotAllowedCode is the HTTP code returned for type DeletePatientMethodNotAllowed
const DeletePatientMethodNotAllowedCode int = 405

/*DeletePatientMethodNotAllowed Invalid Request Method

swagger:response deletePatientMethodNotAllowed
*/
type DeletePatientMethodNotAllowed struct {
}

// NewDeletePatientMethodNotAllowed creates DeletePatientMethodNotAllowed with default headers values
func NewDeletePatientMethodNotAllowed() *DeletePatientMethodNotAllowed {

	return &DeletePatientMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeletePatientMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
