// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteResultdetailsHandlerFunc turns a function with the right signature into a delete resultdetails handler
type DeleteResultdetailsHandlerFunc func(DeleteResultdetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteResultdetailsHandlerFunc) Handle(params DeleteResultdetailsParams) middleware.Responder {
	return fn(params)
}

// DeleteResultdetailsHandler interface for that can handle valid delete resultdetails params
type DeleteResultdetailsHandler interface {
	Handle(DeleteResultdetailsParams) middleware.Responder
}

// NewDeleteResultdetails creates a new http.Handler for the delete resultdetails operation
func NewDeleteResultdetails(ctx *middleware.Context, handler DeleteResultdetailsHandler) *DeleteResultdetails {
	return &DeleteResultdetails{Context: ctx, Handler: handler}
}

/*DeleteResultdetails swagger:route DELETE /resultdetails/{id} deleteResultdetails

deletes a resultdetails

Deletes a resultdetails to the system

*/
type DeleteResultdetails struct {
	Context *middleware.Context
	Handler DeleteResultdetailsHandler
}

func (o *DeleteResultdetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteResultdetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
