// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteResultdetailsOKCode is the HTTP code returned for type DeleteResultdetailsOK
const DeleteResultdetailsOKCode int = 200

/*DeleteResultdetailsOK Deleted resultdetails

swagger:response deleteResultdetailsOK
*/
type DeleteResultdetailsOK struct {
	Payload string `json:"body,omitempty"`
}

// NewDeleteResultdetailsOK creates DeleteResultdetailsOK with default headers values
func NewDeleteResultdetailsOK() *DeleteResultdetailsOK {

	return &DeleteResultdetailsOK{}
}

// WithPayload adds the payload to the delete resultdetails o k response
func (o *DeleteResultdetailsOK) WithPayload(payload string) *DeleteResultdetailsOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DeleteResultdetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
