// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePatientOKCode is the HTTP code returned for type DeletePatientOK
const DeletePatientOKCode int = 200

/*DeletePatientOK Deleted item

swagger:response deletePatientOK
*/
type DeletePatientOK struct {
	Payload string `json:"body,omitempty"`
}

// NewDeletePatientOK creates DeletePatientOK with default headers values
func NewDeletePatientOK() *DeletePatientOK {

	return &DeletePatientOK{}
}

// WithPayload adds the payload to the deleter patient o k response
func (o *DeletePatientOK) WithPayload(payload string) *DeletePatientOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DeletePatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
