// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteResultdetailsOKCode is the HTTP code returned for type DeleteResultdetailsOK
const DeleteResultdetailsOKCode int = 200

/*DeleteResultdetailsOK Deleted resultdetails

swagger:response deleteResultdetailsOK
*/
type DeleteResultdetailsOK struct {
}

// NewDeleteResultdetailsOK creates DeleteResultdetailsOK with default headers values
func NewDeleteResultdetailsOK() *DeleteResultdetailsOK {

	return &DeleteResultdetailsOK{}
}

// WriteResponse to the client
func (o *DeleteResultdetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteResultdetailsMethodNotAllowedCode is the HTTP code returned for type DeleteResultdetailsMethodNotAllowed
const DeleteResultdetailsMethodNotAllowedCode int = 405

/*DeleteResultdetailsMethodNotAllowed Invalid Request Method

swagger:response deleteResultdetailsMethodNotAllowed
*/
type DeleteResultdetailsMethodNotAllowed struct {
}

// NewDeleteResultdetailsMethodNotAllowed creates DeleteResultdetailsMethodNotAllowed with default headers values
func NewDeleteResultdetailsMethodNotAllowed() *DeleteResultdetailsMethodNotAllowed {

	return &DeleteResultdetailsMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteResultdetailsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
