// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePatientHandlerFunc turns a function with the right signature into a delete patient handler
type DeletePatientHandlerFunc func(DeletePatientParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePatientHandlerFunc) Handle(params DeletePatientParams) middleware.Responder {
	return fn(params)
}

// DeletePatientHandler interface for that can handle valid delete patient params
type DeletePatientHandler interface {
	Handle(DeletePatientParams) middleware.Responder
}

// NewDeletePatient creates a new http.Handler for the delete patient operation
func NewDeletePatient(ctx *middleware.Context, handler DeletePatientHandler) *DeletePatient {
	return &DeletePatient{Context: ctx, Handler: handler}
}

/*DeletePatient swagger:route DELETE /patient/{id} deletePatient

deletes a patient

Deletes a patient to the system

*/
type DeletePatient struct {
	Context *middleware.Context
	Handler DeletePatientHandler
}

func (o *DeletePatient) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePatientParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
