// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteSampleOKCode is the HTTP code returned for type DeleteSampleOK
const DeleteSampleOKCode int = 200

/*DeleteSampleOK Deleted sample

swagger:response deleteSampleOK
*/
type DeleteSampleOK struct {
}

// NewDeleteSampleOK creates DeleteSampleOK with default headers values
func NewDeleteSampleOK() *DeleteSampleOK {

	return &DeleteSampleOK{}
}

// WriteResponse to the client
func (o *DeleteSampleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteSampleMethodNotAllowedCode is the HTTP code returned for type DeleteSampleMethodNotAllowed
const DeleteSampleMethodNotAllowedCode int = 405

/*DeleteSampleMethodNotAllowed Invalid Request Method

swagger:response deleteSampleMethodNotAllowed
*/
type DeleteSampleMethodNotAllowed struct {
}

// NewDeleteSampleMethodNotAllowed creates DeleteSampleMethodNotAllowed with default headers values
func NewDeleteSampleMethodNotAllowed() *DeleteSampleMethodNotAllowed {

	return &DeleteSampleMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteSampleMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
