// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Bio-core/jtree/models"
)

// GetSampleOKCode is the HTTP code returned for type GetSampleOK
const GetSampleOKCode int = 200

/*GetSampleOK OK

swagger:response getSampleOK
*/
type GetSampleOK struct {

	/*
	  In: Body
	*/
	Payload models.GetSampleOKBody `json:"body,omitempty"`
}

// NewGetSampleOK creates GetSampleOK with default headers values
func NewGetSampleOK() *GetSampleOK {
	return &GetSampleOK{}
}

// WithPayload adds the payload to the get sample o k response
func (o *GetSampleOK) WithPayload(payload models.GetSampleOKBody) *GetSampleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sample o k response
func (o *GetSampleOK) SetPayload(payload models.GetSampleOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSampleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetSampleOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSampleNotFoundCode is the HTTP code returned for type GetSampleNotFound
const GetSampleNotFoundCode int = 404

/*GetSampleNotFound Sample not found

swagger:response getSampleNotFound
*/
type GetSampleNotFound struct {
}

// NewGetSampleNotFound creates GetSampleNotFound with default headers values
func NewGetSampleNotFound() *GetSampleNotFound {
	return &GetSampleNotFound{}
}

// WriteResponse to the client
func (o *GetSampleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
