// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetBiosampleHandlerFunc turns a function with the right signature into a get biosample handler
type GetBiosampleHandlerFunc func(GetBiosampleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBiosampleHandlerFunc) Handle(params GetBiosampleParams) middleware.Responder {
	return fn(params)
}

// GetBiosampleHandler interface for that can handle valid get biosample params
type GetBiosampleHandler interface {
	Handle(GetBiosampleParams) middleware.Responder
}

// NewGetBiosample creates a new http.Handler for the get biosample operation
func NewGetBiosample(ctx *middleware.Context, handler GetBiosampleHandler) *GetBiosample {
	return &GetBiosample{Context: ctx, Handler: handler}
}

/*GetBiosample swagger:route GET /biosample/{biosampleId} getBiosample

Returns an biosample by ID.

*/
type GetBiosample struct {
	Context *middleware.Context
	Handler GetBiosampleHandler
}

func (o *GetBiosample) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBiosampleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
