// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSampleHandlerFunc turns a function with the right signature into a get sample handler
type GetSampleHandlerFunc func(GetSampleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSampleHandlerFunc) Handle(params GetSampleParams) middleware.Responder {
	return fn(params)
}

// GetSampleHandler interface for that can handle valid get sample params
type GetSampleHandler interface {
	Handle(GetSampleParams) middleware.Responder
}

// NewGetSample creates a new http.Handler for the get sample operation
func NewGetSample(ctx *middleware.Context, handler GetSampleHandler) *GetSample {
	return &GetSample{Context: ctx, Handler: handler}
}

/*GetSample swagger:route GET /sample/{sampleId} getSample

Returns a sample by ID.

*/
type GetSample struct {
	Context *middleware.Context
	Handler GetSampleHandler
}

func (o *GetSample) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSampleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
