// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBiosampleParams creates a new GetBiosampleParams object
// with the default values initialized.
func NewGetBiosampleParams() GetBiosampleParams {
	var ()
	return GetBiosampleParams{}
}

// GetBiosampleParams contains all the bound params for the get biosample operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBiosample
type GetBiosampleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	BiosampleID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetBiosampleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rBiosampleID, rhkBiosampleID, _ := route.Params.GetOK("biosampleId")
	if err := o.bindBiosampleID(rBiosampleID, rhkBiosampleID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBiosampleParams) bindBiosampleID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("biosampleId", "path", "strfmt.UUID", raw)
	}
	o.BiosampleID = *(value.(*strfmt.UUID))

	return nil
}
