// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPatientColumnsHandlerFunc turns a function with the right signature into a get patient columns handler
type GetPatientColumnsHandlerFunc func(GetPatientColumnsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPatientColumnsHandlerFunc) Handle(params GetPatientColumnsParams) middleware.Responder {
	return fn(params)
}

// GetPatientColumnsHandler interface for that can handle valid get patient columns params
type GetPatientColumnsHandler interface {
	Handle(GetPatientColumnsParams) middleware.Responder
}

// NewGetPatientColumns creates a new http.Handler for the get patient columns operation
func NewGetPatientColumns(ctx *middleware.Context, handler GetPatientColumnsHandler) *GetPatientColumns {
	return &GetPatientColumns{Context: ctx, Handler: handler}
}

/*GetPatientColumns swagger:route GET /patient/columns getPatientColumns

gets columns

gets column names

*/
type GetPatientColumns struct {
	Context *middleware.Context
	Handler GetPatientColumnsHandler
}

func (o *GetPatientColumns) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPatientColumnsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
