// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Bio-core/jtree/models"
)

// GetPatientOKCode is the HTTP code returned for type GetPatientOK
const GetPatientOKCode int = 200

/*GetPatientOK OK

swagger:response getPatientOK
*/
type GetPatientOK struct {

	/*
	  In: Body
	*/
	Payload models.GetPatientOKBody `json:"body,omitempty"`
}

// NewGetPatientOK creates GetPatientOK with default headers values
func NewGetPatientOK() *GetPatientOK {
	return &GetPatientOK{}
}

// WithPayload adds the payload to the get patient o k response
func (o *GetPatientOK) WithPayload(payload models.GetPatientOKBody) *GetPatientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get patient o k response
func (o *GetPatientOK) SetPayload(payload models.GetPatientOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetPatientOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetPatientNotFoundCode is the HTTP code returned for type GetPatientNotFound
const GetPatientNotFoundCode int = 404

/*GetPatientNotFound patient not found

swagger:response getPatientNotFound
*/
type GetPatientNotFound struct {
}

// NewGetPatientNotFound creates GetPatientNotFound with default headers values
func NewGetPatientNotFound() *GetPatientNotFound {
	return &GetPatientNotFound{}
}

// WriteResponse to the client
func (o *GetPatientNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
