// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bio-core/jtree/models"
)

// GetBiosampleOKCode is the HTTP code returned for type GetBiosampleOK
const GetBiosampleOKCode int = 200

/*GetBiosampleOK OK

swagger:response getBiosampleOK
*/
type GetBiosampleOK struct {

	/*
	  In: Body
	*/
	Payload models.GetBiosampleOKBody `json:"body,omitempty"`
}

// NewGetBiosampleOK creates GetBiosampleOK with default headers values
func NewGetBiosampleOK() *GetBiosampleOK {
	return &GetBiosampleOK{}
}

// WithPayload adds the payload to the get biosample o k response
func (o *GetBiosampleOK) WithPayload(payload models.GetBiosampleOKBody) *GetBiosampleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get biosample o k response
func (o *GetBiosampleOK) SetPayload(payload models.GetBiosampleOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBiosampleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetBiosampleOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetBiosampleNotFoundCode is the HTTP code returned for type GetBiosampleNotFound
const GetBiosampleNotFoundCode int = 404

/*GetBiosampleNotFound Biosample not found

swagger:response getBiosampleNotFound
*/
type GetBiosampleNotFound struct {
}

// NewGetBiosampleNotFound creates GetBiosampleNotFound with default headers values
func NewGetBiosampleNotFound() *GetBiosampleNotFound {
	return &GetBiosampleNotFound{}
}

// WriteResponse to the client
func (o *GetBiosampleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
