// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPatientColumnsOKCode is the HTTP code returned for type GetPatientColumnsOK
const GetPatientColumnsOKCode int = 200

/*GetPatientColumnsOK columns

swagger:response getPatientColumnsOK
*/
type GetPatientColumnsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetPatientColumnsOK creates GetPatientColumnsOK with default headers values
func NewGetPatientColumnsOK() *GetPatientColumnsOK {
	return &GetPatientColumnsOK{}
}

// WithPayload adds the payload to the get patient columns o k response
func (o *GetPatientColumnsOK) WithPayload(payload []string) *GetPatientColumnsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get patient columns o k response
func (o *GetPatientColumnsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPatientColumnsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetPatientColumnsBadRequestCode is the HTTP code returned for type GetPatientColumnsBadRequest
const GetPatientColumnsBadRequestCode int = 400

/*GetPatientColumnsBadRequest bad input parameter

swagger:response getPatientColumnsBadRequest
*/
type GetPatientColumnsBadRequest struct {
}

// NewGetPatientColumnsBadRequest creates GetPatientColumnsBadRequest with default headers values
func NewGetPatientColumnsBadRequest() *GetPatientColumnsBadRequest {
	return &GetPatientColumnsBadRequest{}
}

// WriteResponse to the client
func (o *GetPatientColumnsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
