// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bio-core/jtree/models"
)

// GetIndividualOKCode is the HTTP code returned for type GetIndividualOK
const GetIndividualOKCode int = 200

/*GetIndividualOK OK

swagger:response getIndividualOK
*/
type GetIndividualOK struct {

	/*
	  In: Body
	*/
	Payload models.GetIndividualOKBody `json:"body,omitempty"`
}

// NewGetIndividualOK creates GetIndividualOK with default headers values
func NewGetIndividualOK() *GetIndividualOK {
	return &GetIndividualOK{}
}

// WithPayload adds the payload to the get individual o k response
func (o *GetIndividualOK) WithPayload(payload models.GetIndividualOKBody) *GetIndividualOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get individual o k response
func (o *GetIndividualOK) SetPayload(payload models.GetIndividualOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndividualOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetIndividualOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetIndividualNotFoundCode is the HTTP code returned for type GetIndividualNotFound
const GetIndividualNotFoundCode int = 404

/*GetIndividualNotFound individual not found

swagger:response getIndividualNotFound
*/
type GetIndividualNotFound struct {
}

// NewGetIndividualNotFound creates GetIndividualNotFound with default headers values
func NewGetIndividualNotFound() *GetIndividualNotFound {
	return &GetIndividualNotFound{}
}

// WriteResponse to the client
func (o *GetIndividualNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
