// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIndividualHandlerFunc turns a function with the right signature into a get individual handler
type GetIndividualHandlerFunc func(GetIndividualParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIndividualHandlerFunc) Handle(params GetIndividualParams) middleware.Responder {
	return fn(params)
}

// GetIndividualHandler interface for that can handle valid get individual params
type GetIndividualHandler interface {
	Handle(GetIndividualParams) middleware.Responder
}

// NewGetIndividual creates a new http.Handler for the get individual operation
func NewGetIndividual(ctx *middleware.Context, handler GetIndividualHandler) *GetIndividual {
	return &GetIndividual{Context: ctx, Handler: handler}
}

/*GetIndividual swagger:route GET /individuals/{individualId} getIndividual

Returns an individual by ID.

*/
type GetIndividual struct {
	Context *middleware.Context
	Handler GetIndividualHandler
}

func (o *GetIndividual) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIndividualParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
