package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Bio-core/jtree/models"
)

// LogoutOKCode is the HTTP code returned for type GetSampleOK
const LogoutOKCode int = 200

/*LogoutOK OK

swagger:response getSampleOK
*/
type LogoutOK struct {

	/*
	  In: Body
	*/
	Payload models.LogoutOKBody `json:"body,omitempty"`
}

// NewGetSampleOK creates GetSampleOK with default headers values
func NewLogoutOK() *LogoutOK {
	return &LogoutOK{}
}

// WithPayload adds the payload to the get sample o k response
func (o *LogoutOK) WithPayload(payload models.LogoutOKBody) *LogoutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sample o k response
func (o *LogoutOK) SetPayload(payload models.LogoutOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSampleNotFoundCode is the HTTP code returned for type GetSampleNotFound
const LogoutNotFoundCode int = 404

/*GetSampleNotFound Sample not found

swagger:response getSampleNotFound
*/
type LogoutNotFound struct {
}

// NewGetSampleNotFound creates GetSampleNotFound with default headers values
func NewLogoutNotFound() *LogoutNotFound {
	return &LogoutNotFound{}
}

// WriteResponse to the client
func (o *LogoutNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
