// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ljdursi/candig_mds/models"
)

// SearchIndividualOKCode is the HTTP code returned for type SearchIndividualOK
const SearchIndividualOKCode int = 200

/*SearchIndividualOK search results matching criteria

swagger:response searchIndividualOK
*/
type SearchIndividualOK struct {

	/*
	  In: Body
	*/
	Payload models.SearchIndividualOKBody `json:"body,omitempty"`
}

// NewSearchIndividualOK creates SearchIndividualOK with default headers values
func NewSearchIndividualOK() *SearchIndividualOK {
	return &SearchIndividualOK{}
}

// WithPayload adds the payload to the search individual o k response
func (o *SearchIndividualOK) WithPayload(payload models.SearchIndividualOKBody) *SearchIndividualOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search individual o k response
func (o *SearchIndividualOK) SetPayload(payload models.SearchIndividualOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchIndividualOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.SearchIndividualOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// SearchIndividualBadRequestCode is the HTTP code returned for type SearchIndividualBadRequest
const SearchIndividualBadRequestCode int = 400

/*SearchIndividualBadRequest bad input parameter

swagger:response searchIndividualBadRequest
*/
type SearchIndividualBadRequest struct {
}

// NewSearchIndividualBadRequest creates SearchIndividualBadRequest with default headers values
func NewSearchIndividualBadRequest() *SearchIndividualBadRequest {
	return &SearchIndividualBadRequest{}
}

// WriteResponse to the client
func (o *SearchIndividualBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
