// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ljdursi/candig_mds/models"
)

// SearchBiosampleOKCode is the HTTP code returned for type SearchBiosampleOK
const SearchBiosampleOKCode int = 200

/*SearchBiosampleOK search results matching criteria

swagger:response searchBiosampleOK
*/
type SearchBiosampleOK struct {

	/*
	  In: Body
	*/
	Payload models.SearchBiosampleOKBody `json:"body,omitempty"`
}

// NewSearchBiosampleOK creates SearchBiosampleOK with default headers values
func NewSearchBiosampleOK() *SearchBiosampleOK {
	return &SearchBiosampleOK{}
}

// WithPayload adds the payload to the search biosample o k response
func (o *SearchBiosampleOK) WithPayload(payload models.SearchBiosampleOKBody) *SearchBiosampleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search biosample o k response
func (o *SearchBiosampleOK) SetPayload(payload models.SearchBiosampleOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchBiosampleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.SearchBiosampleOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// SearchBiosampleBadRequestCode is the HTTP code returned for type SearchBiosampleBadRequest
const SearchBiosampleBadRequestCode int = 400

/*SearchBiosampleBadRequest bad input parameter

swagger:response searchBiosampleBadRequest
*/
type SearchBiosampleBadRequest struct {
}

// NewSearchBiosampleBadRequest creates SearchBiosampleBadRequest with default headers values
func NewSearchBiosampleBadRequest() *SearchBiosampleBadRequest {
	return &SearchBiosampleBadRequest{}
}

// WriteResponse to the client
func (o *SearchBiosampleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
