// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SearchIndividualHandlerFunc turns a function with the right signature into a search individual handler
type SearchIndividualHandlerFunc func(SearchIndividualParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchIndividualHandlerFunc) Handle(params SearchIndividualParams) middleware.Responder {
	return fn(params)
}

// SearchIndividualHandler interface for that can handle valid search individual params
type SearchIndividualHandler interface {
	Handle(SearchIndividualParams) middleware.Responder
}

// NewSearchIndividual creates a new http.Handler for the search individual operation
func NewSearchIndividual(ctx *middleware.Context, handler SearchIndividualHandler) *SearchIndividual {
	return &SearchIndividual{Context: ctx, Handler: handler}
}

/*SearchIndividual swagger:route GET /individuals/search searchIndividual

searches individuals

By passing in the appropriate options, you can search for
available individuals


*/
type SearchIndividual struct {
	Context *middleware.Context
	Handler SearchIndividualHandler
}

func (o *SearchIndividual) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSearchIndividualParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
