// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SearchBiosampleHandlerFunc turns a function with the right signature into a search biosample handler
type SearchBiosampleHandlerFunc func(SearchBiosampleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchBiosampleHandlerFunc) Handle(params SearchBiosampleParams) middleware.Responder {
	return fn(params)
}

// SearchBiosampleHandler interface for that can handle valid search biosample params
type SearchBiosampleHandler interface {
	Handle(SearchBiosampleParams) middleware.Responder
}

// NewSearchBiosample creates a new http.Handler for the search biosample operation
func NewSearchBiosample(ctx *middleware.Context, handler SearchBiosampleHandler) *SearchBiosample {
	return &SearchBiosample{Context: ctx, Handler: handler}
}

/*SearchBiosample swagger:route GET /biosamples/search searchBiosample

searches biosamples

By passing in the appropriate options, you can search for
available biosample


*/
type SearchBiosample struct {
	Context *middleware.Context
	Handler SearchBiosampleHandler
}

func (o *SearchBiosample) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSearchBiosampleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
