// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchIndividualParams creates a new SearchIndividualParams object
// with the default values initialized.
func NewSearchIndividualParams() SearchIndividualParams {
	var ()
	return SearchIndividualParams{}
}

// SearchIndividualParams contains all the bound params for the search individual operation
// typically these are obtained from a http.Request
//
// swagger:parameters searchIndividual
type SearchIndividualParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*pass an optional search string for looking up inventory
	  In: query
	  Collection Format: multi
	*/
	SearchString []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *SearchIndividualParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSearchString, qhkSearchString, _ := qs.GetOK("searchString")
	if err := o.bindSearchString(qSearchString, qhkSearchString, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SearchIndividualParams) bindSearchString(rawData []string, hasKey bool, formats strfmt.Registry) error {

	searchStringIC := rawData

	if len(searchStringIC) == 0 {
		return nil
	}

	var searchStringIR []string
	for _, searchStringIV := range searchStringIC {
		searchStringI := searchStringIV

		searchStringIR = append(searchStringIR, searchStringI)
	}

	o.SearchString = searchStringIR

	return nil
}
