// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateResultdetailsHandlerFunc turns a function with the right signature into a update resultdetails handler
type UpdateResultdetailsHandlerFunc func(UpdateResultdetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResultdetailsHandlerFunc) Handle(params UpdateResultdetailsParams) middleware.Responder {
	return fn(params)
}

// UpdateResultdetailsHandler interface for that can handle valid update resultdetails params
type UpdateResultdetailsHandler interface {
	Handle(UpdateResultdetailsParams) middleware.Responder
}

// NewUpdateResultdetails creates a new http.Handler for the update resultdetails operation
func NewUpdateResultdetails(ctx *middleware.Context, handler UpdateResultdetailsHandler) *UpdateResultdetails {
	return &UpdateResultdetails{Context: ctx, Handler: handler}
}

/*UpdateResultdetails swagger:route PUT /resultdetails/{id} updateResultdetails

updates a resultdetails

Updates a resultdetails to the system

*/
type UpdateResultdetails struct {
	Context *middleware.Context
	Handler UpdateResultdetailsHandler
}

func (o *UpdateResultdetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateResultdetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
