// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateResultdetailsOKCode is the HTTP code returned for type UpdateResultdetailsOK
const UpdateResultdetailsOKCode int = 200

/*UpdateResultdetailsOK resultdetails updated

swagger:response updateResultdetailsOK
*/
type UpdateResultdetailsOK struct {
	Payload string `json:"body,omitempty"`
}

// NewUpdateResultdetailsOK creates UpdateResultdetailsOK with default headers values
func NewUpdateResultdetailsOK() *UpdateResultdetailsOK {

	return &UpdateResultdetailsOK{}
}

// WithPayload adds the payload to the update resultdetails o k response
func (o *UpdateResultdetailsOK) WithPayload(payload string) *UpdateResultdetailsOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *UpdateResultdetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
