// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateSampleHandlerFunc turns a function with the right signature into a update sample handler
type UpdateSampleHandlerFunc func(UpdateSampleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSampleHandlerFunc) Handle(params UpdateSampleParams) middleware.Responder {
	return fn(params)
}

// UpdateSampleHandler interface for that can handle valid update sample params
type UpdateSampleHandler interface {
	Handle(UpdateSampleParams) middleware.Responder
}

// NewUpdateSample creates a new http.Handler for the update sample operation
func NewUpdateSample(ctx *middleware.Context, handler UpdateSampleHandler) *UpdateSample {
	return &UpdateSample{Context: ctx, Handler: handler}
}

/*UpdateSample swagger:route PUT /sample/{id} updateSample

updates a sample

Updates a sample to the system

*/
type UpdateSample struct {
	Context *middleware.Context
	Handler UpdateSampleHandler
}

func (o *UpdateSample) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateSampleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
