// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateSampleOKCode is the HTTP code returned for type UpdateSampleOK
const UpdateSampleOKCode int = 200

/*UpdateSampleOK sample created

swagger:response updateSampleOK
*/
type UpdateSampleOK struct {
	Payload string `json:"body,omitempty"`
}

// NewUpdateSampleOK creates UpdateSampleOK with default headers values
func NewUpdateSampleOK() *UpdateSampleOK {

	return &UpdateSampleOK{}
}

// WithPayload adds the payload to the update sample o k response
func (o *UpdateSampleOK) WithPayload(payload string) *UpdateSampleOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *UpdateSampleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
