// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePatientCreatedCode is the HTTP code returned for type UpdatePatientCreated
const UpdatePatientCreatedCode int = 201

/*UpdatePatientCreated works

swagger:response updatePatientCreated
*/
type UpdatePatientCreated struct {
	Payload string `json:"body,omitempty"`
}

// NewUpdatePatientCreated creates UpdatePatientCreated with default headers values
func NewUpdatePatientCreated() *UpdatePatientCreated {

	return &UpdatePatientCreated{}
}

// WithPayload adds the payload to the add patient o k response
func (o *UpdatePatientCreated) WithPayload(payload string) *UpdatePatientCreated {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *UpdatePatientCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
