// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Metadata API",
    "title": "Candig Metadata API",
    "contact": {
      "email": "info@distributedgenomics.ca"
    },
    "license": {
      "name": "GPL",
      "url": "https://www.gnu.org/licenses/gpl-3.0.en.html"
    },
    "version": "0.1.0"
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/CanDIG/metadata/0.1.0",
  "paths": {
    "/biosample": {
      "post": {
        "description": "Adds a biosample to the system",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "adds a biosample",
        "operationId": "addBiosample",
        "parameters": [
          {
            "description": "Biosample",
            "name": "biosample",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Biosample"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "item created"
          },
          "400": {
            "description": "invalid input, object invalid"
          },
          "409": {
            "description": "an existing item already exists"
          }
        }
      }
    },
    "/biosample/{biosampleId}": {
      "get": {
        "summary": "Returns an biosample by ID.",
        "operationId": "getBiosample",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Biosample"
              }
            }
          },
          "404": {
            "description": "Biosample not found"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "biosampleId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/biosamples/search": {
      "get": {
        "description": "By passing in the appropriate options, you can search for\navailable biosample\n",
        "produces": [
          "application/json"
        ],
        "summary": "searches biosamples",
        "operationId": "searchBiosample",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "description": "pass an optional search string for looking up inventory",
            "name": "searchString",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "search results matching criteria",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Biosample"
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    },
    "/individual": {
      "post": {
        "description": "Adds an individual to the system",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "adds an individual item",
        "operationId": "addIndividual",
        "parameters": [
          {
            "description": "Individual",
            "name": "individual",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Individual"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "item created"
          },
          "400": {
            "description": "invalid input, object invalid"
          },
          "409": {
            "description": "an existing item already exists"
          }
        }
      }
    },
    "/individual/{individualId}": {
      "get": {
        "summary": "Returns an individual by ID.",
        "operationId": "getIndividual",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Individual"
              }
            }
          },
          "404": {
            "description": "individual not found"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "individualId",
          "in": "path",
          "required": true
        }
      ]
    },
    "/individuals/search": {
      "get": {
        "description": "By passing in the appropriate options, you can search for\navailable individuals\n",
        "produces": [
          "application/json"
        ],
        "summary": "searches individuals",
        "operationId": "searchIndividual",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "description": "pass an optional search string for looking up inventory",
            "name": "searchString",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "search results matching criteria",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Individual"
              }
            }
          },
          "400": {
            "description": "bad input parameter"
          }
        }
      }
    }
  },
  "definitions": {
    "Attribute": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "Attributes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Attribute"
      }
    },
    "Biosample": {
      "type": "object",
      "required": [
        "collectionAge",
        "description",
        "individualId",
        "name"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/Attributes"
        },
        "collectionAge": {
          "type": "string"
        },
        "createdDate": {
          "type": "string",
          "format": "date"
        },
        "description": {
          "type": "string"
        },
        "disease": {
          "$ref": "#/definitions/OntologyTerm"
        },
        "id": {
          "type": "string",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "individualId": {
          "type": "string"
        },
        "name": {
          "type": "string",
          "example": "CANDIG-BCGSC-SM-d290f1ee-6c54-4b01-90e6"
        },
        "updatedDate": {
          "type": "string",
          "format": "date"
        }
      },
      "example": {
        "attributes": "",
        "collectionAge": "collectionAge",
        "createdDate": "2000-01-23",
        "description": "description",
        "disease": {
          "ontology": "http://purl.obolibrary.org/obo",
          "term": "male genotypic sex",
          "termId": "PATO:0020001"
        },
        "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
        "individualId": "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
        "name": "CANDIG-BCGSC-SM-d290f1ee-6c54-4b01-90e6",
        "updatedDate": "2000-01-23"
      }
    },
    "Individual": {
      "type": "object",
      "required": [
        "description",
        "name"
      ],
      "properties": {
        "attributes": {
          "$ref": "#/definitions/Attributes"
        },
        "createdDate": {
          "type": "string",
          "format": "date"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "name": {
          "type": "string",
          "example": "CANDIG-BCGSC-IN-d290f1ee-6c54-4b01-90e6"
        },
        "sex": {
          "$ref": "#/definitions/OntologyTerm"
        },
        "species": {
          "$ref": "#/definitions/OntologyTerm"
        },
        "updatedDate": {
          "type": "string",
          "format": "date"
        }
      },
      "example": {
        "attributes": "",
        "createdDate": "2000-01-23",
        "description": "description",
        "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
        "name": "CANDIG-BCGSC-IN-d290f1ee-6c54-4b01-90e6",
        "sex": {
          "ontology": "http://purl.obolibrary.org/obo",
          "term": "male genotypic sex",
          "termId": "PATO:0020001"
        },
        "species": {
          "ontology": "http://purl.obolibrary.org/obo",
          "term": "male genotypic sex",
          "termId": "PATO:0020001"
        },
        "updatedDate": "2000-01-23"
      }
    },
    "OntologyTerm": {
      "type": "object",
      "required": [
        "term",
        "termId"
      ],
      "properties": {
        "ontology": {
          "type": "string",
          "format": "url",
          "example": "http://purl.obolibrary.org/obo"
        },
        "term": {
          "type": "string",
          "example": "male genotypic sex"
        },
        "termId": {
          "type": "string",
          "example": "PATO:0020001"
        }
      },
      "example": {
        "ontology": "http://purl.obolibrary.org/obo",
        "term": "male genotypic sex",
        "termId": "PATO:0020001"
      }
    }
  }
}`))
}
