// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Individual individual
// swagger:model Individual
type Individual struct {

	// attributes
	Attributes Attributes `json:"attributes"`

	// created date
	CreatedDate strfmt.Date `json:"createdDate,omitempty"`

	// description
	// Required: true
	Description *string `json:"description"`

	// id
	ID string `json:"id,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// sex
	Sex *OntologyTerm `json:"sex,omitempty"`

	// species
	Species *OntologyTerm `json:"species,omitempty"`

	// updated date
	UpdatedDate strfmt.Date `json:"updatedDate,omitempty"`
}

// Validate validates this individual
func (m *Individual) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSex(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSpecies(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Individual) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *Individual) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Individual) validateSex(formats strfmt.Registry) error {

	if swag.IsZero(m.Sex) { // not required
		return nil
	}

	if m.Sex != nil {

		if err := m.Sex.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sex")
			}
			return err
		}
	}

	return nil
}

func (m *Individual) validateSpecies(formats strfmt.Registry) error {

	if swag.IsZero(m.Species) { // not required
		return nil
	}

	if m.Species != nil {

		if err := m.Species.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("species")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Individual) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Individual) UnmarshalBinary(b []byte) error {
	var res Individual
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
